#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 30 15:38:09 2018

@author: sebastianorbell
"""

# Transform tensors from radical principal axis frame to molecular frame
import numpy as np

def transform(N,T):
    T_prime = np.matmul(np.transpose(N),np.matmul(T,N))
    return T_prime
